# Generated by Django 4.2.7 on 2023-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_model_pr_stock"),
        ("users", "0002_alter_address_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="shopping_item",
            field=models.ManyToManyField(to="product.product_model"),
        ),
    ]
