# Generated by Django 4.2.7 on 2023-11-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_model_pr_stock"),
        ("users", "0003_alter_shoppingcart_shopping_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="whishlist_item",
            field=models.ManyToManyField(to="product.product_model"),
        ),
    ]
