# Generated by Django 4.2.7 on 2023-11-12 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product_model",
            fields=[
                (
                    "product_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("pr_desc", models.TextField()),
                ("pr_price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("pr_date", models.DateTimeField(auto_now_add=True)),
                ("pr_m_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product_image",
            fields=[
                (
                    "product_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("pr_img", models.ImageField(upload_to="product/")),
                (
                    "prid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="product.product_model",
                    ),
                ),
            ],
        ),
    ]
