# Generated by Django 4.2.7 on 2023-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_model",
            name="pr_stock",
            field=models.IntegerField(default=10),
        ),
    ]
