# Generated by Django 4.2.7 on 2023-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="date_of_payment",
            field=models.DateTimeField(null=True),
        ),
    ]
